display_name: MQTT Browser
package_name: mqttbrowser

maintainer:
  name: Paul Maik Rempel
  email: paul.rempel@linguwerk.de

priority: optional

section: x11

installed_size: 15700

dependencies:
  - mpv

essential: false

icon: lib/textures/mqtt-browser.png

postuninstall_scripts:
  - echo "Removing my Self :( -- Sorry to see you go."

keywords:
  - MQTT
  - MQTT Browser

generic_name: MQTT Browser

categories:
  - Development
  - Utility

startup_notify: true
